@DemoApplication_HostAddress = http://localhost:5171
@DemoApplication_Token = YOUR_TOKEN_HERE
@DemoApplication_Tanent_Token= YOUR_TENENT_TOKEN_HERE

//Authentication
POST {{DemoApplication_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "test@test.com",
  "name": "Test User",
  "password": "test1234"
}

###
POST {{DemoApplication_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test1234"
}

###
POST {{DemoApplication_HostAddress}}/api/auth/switch-restaurant
Authorization: Bearer {{DemoApplication_Token}}
Content-Type: application/json

{
  "restaurantId": 2
}
###

// Reservations

GET {{DemoApplication_HostAddress}}/api/2/reservations
Authorization: Bearer {{DemoApplication_Token}}

###
POST {{DemoApplication_HostAddress}}/api/2/reservations
Authorization: Bearer {{DemoApplication_Token}}
Content-Type: application/json

{
  "tableId": 12,
  "customerName": "Test Customer 1",
  "startTime": "2026-08-15T14:30:05Z",
  "endTime": "2026-08-15T16:30:05Z"
}


###
PUT {{DemoApplication_HostAddress}}/api/2/reservations/4
Authorization: Bearer {{DemoApplication_Token}}
Content-Type: application/json

{
  "tableId": 12,
  "customerName": "Test Customer 6",
  "startTime": "2026-09-15T16:30:05Z",
  "endTime": "2026-09-15T17:30:05Z"
}

###

DELETE {{DemoApplication_HostAddress}}/api/2/reservations/3
Authorization: Bearer {{DemoApplication_Token}}


###

// Restaurants
POST {{DemoApplication_HostAddress}}/api/restaurants
Authorization: Bearer {{DemoApplication_Token}}
Content-Type: application/json

{
  "name":"Test Restaurant",
  "ownerId":1
}

###

GET {{DemoApplication_HostAddress}}/api/restaurants
Authorization: Bearer {{DemoApplication_Token}}

###

// Tables

POST {{DemoApplication_HostAddress}}/api/tables
Authorization: Bearer {{DemoApplication_Tanent_Token}}
Content-Type: application/json

{
  "TableNumber":551,
  "Capacity":5
}

###

PUT {{DemoApplication_HostAddress}}/api/tables/2
Authorization: Bearer {{DemoApplication_Tanent_Token}}
Content-Type: application/json

{
  "TableNumber":521,
  "Capacity":8
}

###

DELETE  {{DemoApplication_HostAddress}}/api/tables/2
Authorization: Bearer {{DemoApplication_Tanent_Token}}

###

GET {{DemoApplication_HostAddress}}/api/2/tables
Authorization: Bearer {{DemoApplication_Tanent_Token}}

